# -*- coding: utf-8 -*-
"""2_Question.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DjEk3Zoq6YLfClqbzZKbhMxb7H5pob8G

# **Question 2**

Develop a program to read the three sides of two triangles and
calculate the area of both. Define a function to read the three sides
and call it. Also, define a function to calculate the area. Print the total
area enclosed by both triangles and each triangle's contribution (%)
towards it

 s=(a+b+c)/2
 
 A=sqrt(s*(s-a)*(s-b)*(s-c))
"""

#function to input the side
def side():
  side=int(input("Enter the side:"))
  return (side)

#function to calculate area
def area():
  s1=side()                      #s1,s2,s3- three sides of triangle
  s2=side()
  s3=side()
  semip=(s1+s2+s3)*0.5           #semip=semiperimeter of teh triangle
  calculation=semip*(semip-s1)*(semip-s2)*(semip-s3)
  a=calculation**0.5
  print("Area",a)
  return a

#function to calculate the contribution of each triangle
def contribution(a1,a2):                         #a1- area of first triangle
  print("Total",(a1+a2))                         #a2- area of second triangle
  con1=(a1/(a1+a2))*100                          #con1- contribution of first triangle
  con2=(a2/(a1+a2))*100                          #con2- contribution of second triangle
  print("Contribution of first triangle",con1)
  print("Contribution of second triangle",con2)

#function to be invoked
def main():
  area1=area()
  area2=area()
  contribution(area1,area2)

main()                                            #function invokation

"""**Test Cases**

<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;}
.tg td{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  overflow:hidden;padding:10px 5px;word-break:normal;}
.tg th{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  font-weight:normal;overflow:hidden;padding:10px 5px;word-break:normal;}
.tg .tg-baqh{text-align:center;vertical-align:top}
</style>
<table class="tg">
<thead>
  <tr>
    <th class="tg-baqh">Test Case No.</th>
    <th class="tg-baqh">Description</th>
    <th class="tg-baqh">input</th>
    <th class="tg-baqh">Expected output</th>
    <th class="tg-baqh">Actual output</th>
    <th class="tg-baqh">Result</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td class="tg-baqh">1</td>
    <td class="tg-baqh">Check for area of two triangle</td>
    <td class="tg-baqh">3,4,5<br><br>12,13,5<br></td>
    <td class="tg-baqh">6.0<br><br>36.0<br></td>
    <td class="tg-baqh">6.0<br><br>36.0<br></td>
    <td class="tg-baqh">Pass</td>
  </tr>
  <tr>
    <td class="tg-baqh">2</td>
    <td class="tg-baqh">Check for contribution<br>of each triangle<br></td>
    <td class="tg-baqh">3,4,5<br><br>12,13,5<br></td>
    <td class="tg-baqh">16.66666<br><br>83.3333<br></td>
    <td class="tg-baqh">16.6666<br><br>83.3333<br></td>
    <td class="tg-baqh">Pass</td>
  </tr>
  <tr>
    <td class="tg-baqh">3</td>
    <td class="tg-baqh">Wrong input<br></td>
    <td class="tg-baqh">at</td>
    <td class="tg-baqh">error</td>
    <td class="tg-baqh">error</td>
    <td class="tg-baqh">Pass</td>
  </tr>
</tbody>
</table>
"""