# -*- coding: utf-8 -*-
"""3_Queston.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ijpXwkiX0FLycXe0RhLmWL08Qme_0rW5

# **Question 3**
Develop a program to read the employee's name, code, and basic pay
and calculate the gross salary, deduction, and net salary according to
the following conditions. Define a function to find each of the
components. Finally, generate a payslip.


<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;}
.tg td{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  overflow:hidden;padding:10px 5px;word-break:normal;}
.tg th{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  font-weight:normal;overflow:hidden;padding:10px 5px;word-break:normal;}
.tg .tg-baqh{text-align:center;vertical-align:top}
.tg .tg-mqa1{border-color:#000000;font-weight:bold;text-align:center;vertical-align:top}
.tg .tg-amwm{font-weight:bold;text-align:center;vertical-align:top}
</style>
<table class="tg">
<thead>
  <tr>
    <th class="tg-mqa1">Basic Pay<br>(BP)<br></th>
    <th class="tg-amwm">DA<br> (%)<br></th>
    <th class="tg-amwm">HRA<br> (%)<br></th>
    <th class="tg-amwm">MA<br> <br></th>
    <th class="tg-amwm">PT</th>
    <th class="tg-amwm">PF<br> (%)<br></th>
    <th class="tg-amwm">IT<br> (%)<br></th>
  </tr>
</thead>
<tbody>
  <tr>
    <td class="tg-mqa1">&lt;10000</td>
    <td class="tg-baqh">5</td>
    <td class="tg-baqh">2.5</td>
    <td class="tg-baqh">500</td>
    <td class="tg-baqh">20<br></td>
    <td class="tg-baqh">8</td>
    <td class="tg-baqh">-</td>
  </tr>
  <tr>
    <td class="tg-mqa1">&lt;30000</td>
    <td class="tg-baqh">7.5</td>
    <td class="tg-baqh">5</td>
    <td class="tg-baqh">2500</td>
    <td class="tg-baqh">60</td>
    <td class="tg-baqh">8</td>
    <td class="tg-baqh">-</td>
  </tr>
  <tr>
    <td class="tg-mqa1">&lt;50000</td>
    <td class="tg-baqh">11</td>
    <td class="tg-baqh">7.5</td>
    <td class="tg-baqh">5000</td>
    <td class="tg-baqh">60</td>
    <td class="tg-baqh">11</td>
    <td class="tg-baqh">11</td>
  </tr>
  <tr>
    <td class="tg-mqa1">else<br></td>
    <td class="tg-baqh">25</td>
    <td class="tg-baqh">11</td>
    <td class="tg-baqh">7000</td>
    <td class="tg-baqh">80<br></td>
    <td class="tg-baqh">12</td>
    <td class="tg-baqh">20</td>
  </tr>
</tbody>
</table>


Gross Salary (GS) : BP + DA + HRA + MA

Deduction (D): PT + PF + IT

Net Salary = GS – D
"""

#function to include the details of the employee
def detail():
  name=str(input("Enter the name \t  : "))
  code=int(input("Enter the code \t  : "))
  basic_pay=float(input("Enter the basic pay:"))
  return (name,code,basic_pay)

#function to calculate the Gross Salary
def gross_salary(bp,da,hra,ma):
  gs=bp+da+hra+ma                              #gs- Gross Salary value
  print("Gross salary\t =  \t",gs)
  return gs

#function to claculate Deduction
def deduction(pt,pf,it):                       
  d=pt+pf+it                                   #d- Deduction value
  print("Deduction \t = \t",d)
  return d

#function to calculate the Net Salary
def net_salary(BP,DA,HRA,MA,PT,PF,IT):
  GS=gross_salary(BP,DA,HRA,MA)                #invoke the function gross_salary and return value to GS
  D=deduction(PT,PF,IT)                        #invoke the function deduction and return value to D
  ns=  GS-D                                    #ns- store value of Net Salary
  print("Net Salary \t = \t",ns)

#function to display the input details of employee
def display(nam,cod,basicpay):                 #nam-name   cod-code   
  print("Name of the employee \t :",nam)
  print("Code of the employee \t :",cod)
  print("Basic pay of the employee:",basicpay)

#function from which all other functions are invoked
def main():
  print("Enter the details of the employee.")
  n,c,bp=detail()                             #n-name   c-code      bp-Basic Pay of the employee
  print("\tPay list")
  display(n,c,bp)                             #invoke Display function
  if(bp<10000):
    net_salary(bp,5,2.5,500,20,8,0)           #invoke net_salary function
  elif(bp<30000 and bp>=10000):
    net_salary(bp,7.5,5,2500,60,8,0)
  elif(bp<50000 and bp>=30000):
     net_salary(bp,11,7.5,5000,60,11,11)
  else:
    net_salary(bp,25,11,7000,80,12,20)

main()                        #invoke the main function

"""**Test Cases**

<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;}
.tg td{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  overflow:hidden;padding:10px 5px;word-break:normal;}
.tg th{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  font-weight:normal;overflow:hidden;padding:10px 5px;word-break:normal;}
.tg .tg-c3ow{border-color:inherit;text-align:center;vertical-align:top}
.tg .tg-7btt{border-color:inherit;font-weight:bold;text-align:center;vertical-align:top}
</style>
<table class="tg">
<thead>
  <tr>
    <th class="tg-7btt">Test Cases No.</th>
    <th class="tg-7btt">Descripton</th>
    <th class="tg-7btt">Input</th>
    <th class="tg-7btt">Expected output</th>
    <th class="tg-7btt">Actual output</th>
    <th class="tg-7btt">result</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td class="tg-c3ow">1</td>
    <td class="tg-c3ow">Input basic pay<br>and identity details<br></td>
    <td class="tg-c3ow">10000</td>
    <td class="tg-c3ow">Gross salary&nbsp;&nbsp;&nbsp;= 121512.5<br>Deduction =     68<br>Net Salary&nbsp;&nbsp;&nbsp;&nbsp;=12444.5<br></td>
    <td class="tg-c3ow">Gross salary&nbsp;&nbsp;&nbsp;= 121512.5<br>Deduction =     68<br>Net Salary&nbsp;&nbsp;&nbsp;&nbsp;=12444.5</td>
    <td class="tg-c3ow">Pass<br></td>
  </tr>
  <tr>
    <td class="tg-c3ow">2</td>
    <td class="tg-c3ow">Wrong input</td>
    <td class="tg-c3ow">eret<br></td>
    <td class="tg-c3ow">Error<br></td>
    <td class="tg-c3ow">Error</td>
    <td class="tg-c3ow">Pass<br></td>
  </tr>
</tbody>
</table>
"""