# -*- coding: utf-8 -*-
"""4_Question.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ehjTw8vI8MQ4AHo-BDPISOVvb7GR_ACv

# **Question 4**

Develop a program to perform the following task:

1. Define a function to check whether a number is happy or not.

2. Define a function to print all happy numbers within a range

3. Define a function to print first N happy numbers
"""

#function to check whether happy or sad
def happy(n):
  for i in range(1,101):
    sum=0
    while n!=0:
        digit=n%10                 #digit-each extracted digits stored
        square=digit**2                         
        n=n//10                         
        sum=sum+square                         
    n=sum                         
  return (sum)

#function to print the happy number within range
def happynumber(l,u):               #l-lowerlimit  u-upperlimit
  count=0
  for i in range(l+1,u):
    s=happy(i)                      #invoke happy() function
    if s==1:
      print(i,end=" ")
      count=1                       #count to check whether there is happy number in the range
  print()
  if count==0:                      
    print("There is no happy numbers between this range.")

#Function to print 'n' number of happy numbers
def printnumbers(n):
   count=1                          #count- to check the number of happy numbers printed
   i=1
   while count<=n:
     total=happy(i)                 #invoke happy function
     if total==1:                   #total- condition variable
        print(i,end=" ")
        count+=1
     i=i+1
   print('') 

#function to invoke all above mentioned functions 
def main():
  print("\t HAPPY NUMBER FUNCTIONS")
  print("\tA number is Happy or Sad")
  num=int(input("Enter the number to check:"))
  if happy(num)==1:
    print("Its a Happy number.")
  else:
    print("Its a Sad number.")
  print("\tHappy numbers within a range.")
  lowerlimit=int(input("Enter the Lower limit:"))
  upperlimit=int(input("Enter the Upper limit:"))
  happynumber(lowerlimit,upperlimit)   
  print("\tFirst N happy numbers") 
  N=int(input("Enter the number of terms:"))
  printnumbers(N)                   #N-number of terms to print

main()                              #function invokation

"""**Test Cases**

<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;}
.tg td{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  overflow:hidden;padding:10px 5px;word-break:normal;}
.tg th{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  font-weight:normal;overflow:hidden;padding:10px 5px;word-break:normal;}
.tg .tg-baqh{text-align:center;vertical-align:top}
.tg .tg-c3ow{border-color:inherit;text-align:center;vertical-align:top}
.tg .tg-7btt{border-color:inherit;font-weight:bold;text-align:center;vertical-align:top}
.tg .tg-0lax{text-align:left;vertical-align:top}
</style>
<table class="tg">
<thead>
  <tr>
    <th class="tg-7btt">Test Cases No.</th>
    <th class="tg-7btt">Descripton</th>
    <th class="tg-7btt">Input</th>
    <th class="tg-7btt">Expected output</th>
    <th class="tg-7btt">Actual output</th>
    <th class="tg-7btt">result</th>
  </tr>
</thead>
<tbody>
  <tr>
    <td class="tg-c3ow">1</td>
    <td class="tg-c3ow">Check whether happy or not</td>
    <td class="tg-c3ow">100</td>
    <td class="tg-c3ow">Happy number</td>
    <td class="tg-c3ow">Happy number</td>
    <td class="tg-c3ow">Pass</td>
  </tr>
  <tr>
    <td class="tg-c3ow">2</td>
    <td class="tg-c3ow">Print happy numbers within the <br>range<br></td>
    <td class="tg-c3ow">30<br>45<br></td>
    <td class="tg-c3ow">31 32 44</td>
    <td class="tg-c3ow">31 32 44</td>
    <td class="tg-c3ow">Pass</td>
  </tr>
  <tr>
    <td class="tg-baqh">3</td>
    <td class="tg-baqh">Print N terms of happy numbers</td>
    <td class="tg-0lax">20</td>
    <td class="tg-baqh">1 7 10 13 19 23 28 31 32 44 4<br>9 68 70 79 82 86 91 94 97 100</td>
    <td class="tg-baqh">1 7 10 13 19 23 28 31 32 44 4<br>9 68 70 79 82 86 91 94 97 100</td>
    <td class="tg-0lax">Pass</td>
  </tr>
  <tr>
    <td class="tg-baqh">4</td>
    <td class="tg-baqh">Wrong input<br></td>
    <td class="tg-0lax">ad</td>
    <td class="tg-baqh">error</td>
    <td class="tg-baqh">error</td>
    <td class="tg-0lax">pass</td>
  </tr>
</tbody>
</table>
"""